#!/bin/bash
DIRECTORY=/www/DOMAINNAME/httpdocs
USER=USERNAME
GROUP=USERGROUP
DATE=`date +%Y%m%d`
 
if [ -z "$1" ]
then    echo "Please provide a verion number, for example: sh phpMyAdmin.sh 2.11.2";
else
 
        cd $DIRECTORY;
 
        MYDIRECTORY=`pwd`;
 
        if [ $MYDIRECTORY != $DIRECTORY ]
        then
                echo "Failed to change to the directory";
                pwd;
        else
                wget --directory-prefix=$DIRECTORY http://mesh.dl.sourceforge.net/sourceforge/phpmyadmin/phpMyAdmin-$1-all-languages.tar.bz2
                if [ -f "$DIRECTORY/phpMyAdmin-$1-all-languages.tar.bz2" ]
                then    tar xjvf phpMyAdmin-$1-all-languages.tar.bz2
                        mv -v $DIRECTORY/phpMyAdmin/config.inc.php $DIRECTORY/phpMyAdmin-$1-all-languages/
                        mv $DIRECTORY/phpMyAdmin /$DIRECTORY/phpMyAdmin$DATE
                        mv $DIRECTORY/phpMyAdmin-$1-all-languages $DIRECTORY/phpMyAdmin
                        chown -R $USER:$GROUP $DIRECTORY/phpMyAdmin
                        rm -fv $DIRECTORY/phpMyAdmin-S1-all-languages.tar.bz2
                        echo "The phpMyAdmin update to version " $1 " was successful!"
                        ll
                else
                        echo "The download failed.";
                fi
        fi
fi
